### ISSUE TITLE
SQL Injection Vulnerability

### ISSUE THREAD

**Issue by alongreyber** [NCATS-Gamma/robokache#9]
https://github.com/NCATS-Gamma/robokache/blob/0fc11f3f202531e2b8cbc7082f180893b1f76fae/internal/robokache/get.go#L21-L26

Queries in the `get.go` are built using Sprintf. This allows a SQL Injection attack using a string like the following for the owner variable:

`'DROP TABLE questions;'`

Fix is to replace Sprintf with [db.Prepare](https://golang.org/pkg/database/sql/#DB.Prepare) which accepts placeholders and fills them safely.

**Comment by patrickkwang** [comment]
You may be able to make this safe with `db.Query()`, but just use placeholders for those conditions. I think the use case for `Prepare()` instead of `Query()` is slightly different.
